= Low Level learning

== Looking at the OpCode tables
Ex.

.SAL/SHL
[cols="1,1,1,1,1,4"]
|===
| Opcode   | Instruction      | Op/En | 64-bit Mode | Compat/Leg Mode | Description

| D0/4     | SAL r/m8, 1      | M1    | Valid       | valid           | Multiply r/m8 by 2, once

| C1 /4 ib | SHL r/m16,imm8   | M1    | Valid       | valid           | Multiply r/m32 by 2, once
|===


This is an example of an instruction table that you might see, In this case I
took this from the _Intel 64 and IA-32 Architectures software Developer's
Manual_.

=== Instructions
r::
    "r" stands for a general purpose register, "r/m8" mean a 8 bit register,
    "r/m16" means a 16 bit register.

m::
    A 16-, 32- or 64-bit operand in memory

imm::
    stands for immediate value (e.g., integer constant like 42 or 1335).

rel8::
    A relative address in the range from 128 bytes before the end of the
    instruction to 127 bytes after the end of the instruction.

rel16, rel32::
    A relative address within the same code segment as the instruction
    assembled. The rel16 symbol applies to instructions with an operand-size
    attribute of 16 bits; the rel32 symbol applies to instructions with an
    operand-size attribute of 32 bits

=== Opcodes
REX.W::
    Indicates the use of a REX prefix that affects operand size or instruction
    semantics. The ordering of the REX prefix and other optional/mandatory
    instruction perfixes are discussed in Chapter 2. Note that REX prefixes
    promote legacy instructions to 64-bit behavor are not listed explicitly in
    the opcode column

/Digit::
    A digit between 0 and 7 indicates that the ModR/M byte of the instruction
    uses only the r/m (register or memory) operand. The reg field contains the
    digit that provides an extension to the instruction's opcode.

/r::
    Indicates that the ModR/M byte of the instruction contains a register
    operand and an r/m operand.

cb, cw, cd, cp, co, ct::
     A 1-byte (cb), 2-byte (cw), 4-byte (cd), 6-byte (cp), 8-byte (co) or
     10-byte (ct) value following the opcode. This value is used to specify a
     code offset and possibly a new value for the code segment register.

ib, iw, id, io:: 
    A 1-byte (ib), 2-byte (iw), 4-byte (id) or 8-byte (io) immediate operand to
    the instruction that follows the opcode, ModR/M bytes or scale-indexing
    bytes. The opcode determines if the operand is a signed value. All words,
    doublewords and quadwords are given with the low-order byte first.

+rb, +rw, +rd, +ro::
    Indicates the lower 3 bits of the opcode byte is used to encode the register
    operand without a modR/M byte. The instruction lists the corresponding
    hexadecimal value of the opcode byte with low 3 bits as 000b. In non-64-bit
    mode, a register code, from 0 through 7, is added to the hexadecimal value
    of the opcode byte. In 64-bit mode, indicates the four bit field of REX.b
    and opcode[2:0] field encodes the register operand of the instruction. “+ro”
    is applicable only in 64-bit mode. See Table 3-1 for the codes.

+i::
    A number used in floating-point instructions when one of the operands is
    ST(i) from the FPU register stack. The number i (which can range from 0 to
    7) is added to the hexadecimal byte given at the left of the plus sign to
    form a single opcode byte.




NOTE: Look at Intel 64 and IA-32 Architectures Software Developer's Manual page
      2839

== What's the difference between the CF flag and OF flag.
Carry Flag::
    bits that are carried over in *UNSIGNED* integer arithmetic

Overflow Flag::
    bits that are carried over in *SIGNED* integer arithmetic

== What is that D Flag
The "D" flag determines the size of each element in the stack. It can be
changed, but changing it can result in an unaligned stack if you are not
careful.

== L vs H in registers
"L" is used as a mnemonic lower four bits of the last byte of a register. "H"
is used as a mnemonic as the upper for bits of the last byte of a register. Not
always the case, but sometimes holds true. For example, CL, is the last four
bits of the RCX register.

== Least significant vs Most significant
less significant bits are further the the right. More signifacant bits are
further to the right.

== What does the most significant bit mean in numbers?
It can either be a part of the bit of the number or thing it is trying to
represent if it is a unsigned number. Or it can represent whether a number is
"signed" or "unsigned" if it is a signed number.

== Data types

.datatypes
|===
| Type | Length  | Name
| db   | 8 bits  | Byte
| dw   | 16 bits | Word
| dd   | 32 bits | Double Word
| dq   | 64 bits | Quadword
|===

== lea vs mov
lea:: load effective address
mov:: load value

`lea` loads a pointer to the item you're addressing wheras `mov` loads the
actual value at that address.

== Getting the address of a "variable"
I put variable in quotes because there really isn't variables in assembly.

you can put brackets around a variable to get its address.

ex.

[source, nasm]
----
lea rsi, [variable]
----

square brackets represent *indirect addressing*.

== Registers

=== R_X vs E_X vs _X vs _H vs _L
R_X:: all 64 bits
E_X:: lower 32 bits
_X:: lower 16 bits
_H:: top 4 bits of last byte
_L:: bottom 4 bits of last byte

=== General Purpose Registers
|===
| 64-bit | 32-bit | 16-bit | low 8-bit | high 8-bit | comment
| rax    | eax    | ax     | al        | ah         |
| rbx    | ebx    | bx     | bl        | bh         |
| rcx    | ecx    | cx     | cl        | ch         |
| rcx    | edx    | dx     | dl        | dh         |
| rsi    | esi    | si     | sil       |            |
| rdi    | edi    | di     | dil       |            |
| rbp    | ebp    | bp     | bpl       |            | Base Pointer
| rsp    | esp    | sp     | spl       |            | Stack Pointer
| r8     | r8d    | r8w    | r8b       |            |
| r9     | r9d    | r9w    | r9b       |            |
| r10    | r10d   | r10w   | r10b      |            |
| r11    | r11d   | r11w   | r11b      |            |
| r12    | r12d   | r12w   | r12b      |            |
| r13    | r13d   | r13w   | r13b      |            |
| r14    | r14d   | r14w   | r14b      |            |
| r15    | r15d   | r15w   | r15b      |            |
|===

=== Flag Registers
|===
| Name     | Symbol | Bit | Content

| Carry    | CF     | 0   | Previous instruction had a carry

| parity   | PF     | 2   | Last byte has even number of 1s

| Adjust   | AF     | 4   | BCD operations

| Zero     | ZF     | 6   | Pervious instruction resulted in zero

| Sign     | SF     | 8   | Previous instruction resulted in most significant
                            bit equal to 1

| Overflow | OF     | 11  | Previous instruction resulted in overflow
|===

=== Instruction Pointer Register (rip)
The processor keeps trakc of the next instruction to be executed by storing the
address of the next instruction in rip.

=== xmm and ymm Registers
These registers are used for floating-point calculations and SIMD.


== How to get bits in the carry flag
?

== Main
One file in your assembly program needs "main" defined. This seems to be defined
in the `.text` section.

[source, nasm]
----
section .text
global main
main:
----

== Labels
- Labels look like this `<description>:`
- Local lablels Look like this `.<description>:`

If there is a local label within a global label then the full label name
could loop like this `main.loop`. Like in this example:

[source, nasm]
----
section .text
global main
main:
    .loop
    ; do somethings
    jnz .loop

----

== What is the differnce between SAR and SHR?
SAR sets or clears the most significant bit depending on the sign, While SHR
just clears the most significant bit.

== Jumping

`cmp` sets the approriate flags. `jl` jumps if rax < 42. `jmp` jumps straight to
the `ex` label.

[source, nasm]
----
    cmp rax, 42
    jl yes
    mov rbx, 0
    jmp ex
yes:
    mov rbx, 1
ex:
----

Other::
    1. `ja` (jump if above)/ `jb` (jump if below) for a jump after a comparison
       of _unsigned numbers with cmp_.

    2. `jg` (Jump if greater) / `jl` (jump if less) for _signed_.

    3. `jae` (jump if above or equal), jle (jump if less or equal) and similar

== Function Calls
`Instruction call <address>` is the same as:

[source, nasm]
----
push rip
jmp <address>
----

The address now stored in the stack (for rip contents) is called *return*
*address*.

the first six arguments are rdi, rsi, rdx, rcx, r8, and r9, respectively.

`ret` instruction denotes the function end. same as `pop rip`.

One should not invoke `ret` unless the stack is in exactly the same state as
when the function started.


Callee-saved registers::
    must be restored by the procedure being called.
    rbx, rbp, rsp, r12-r15

Caller-saved registers::
    Should be saved before invoking a function and restored after. All other
    registers are caller-saved.

pattern of calling a function:

- Save all caller-saved registers you want to survive function call (you can use
  push for that)

- Store arguments in the relevent register (rdi, rsi, etc).

- Invoke function returns, rax, will hold the return value.

- Restore caller-saved registers stored before the function call.


NOTE: some system calls also return values - be careful to read the docs!

== Syscalls
syscall instructions implicitly uses rcx. System calls cannot accept more than
six arguments.

All the syscalls are listed in _/usr/include/nasm/unistd.h_ (or something
similar), together with their numbers (the value to put in EAX before you call
int 80h). In ubuntu I found the file in
_/usr/include/x86_64-linux-gnu/asm/unistd_64.h_.

You can checkout `man syscalls` on links to lookup a syscall.


== Different Addressing types

=== Immediate
use the specified value

ex.

[source, nasm]
----
mov rax, 10
----

=== Register
Use the value in teh specified register

[source, nasm]
----
mov rax, rbx
----

[source, nasm]
----
mov rax, [10]; transfers 8 bytes starting at the tenth address into rax
----

[source, nasm]
----
mov r9, 10
mov rax, [r9] ; take the address from the register
----

=== Direct Memory
Use the value at the specified memory address

[source, nasm]
----
mov rdi, 0x172 ; not 100% sure about this
----

=== Base-indexed with scale and discplacement
Most addressing modes are generalized by this mode. The address here is
calculated based on the following components:

----
Address = base + index * scale + displacement
----

- Base is either immediate or a register
- Scale can only be immediate equal to 1, 2, 4, or 8
- Index is immediate or a register 
- Displacement is always immediate

[source, nasm]
----
mov rax, [rbx + 4 * rcx + 9]
mov rax, [4 * r9]
mov rdx, [rax + rbx]
lea rax, [rbx + rbx * 4] ; rax = rbx * 5
add r8, [9 + rbx * 8 + 7]
----

== ATT vs. Intel Syntax
gdb uses ATT syntax by default, but you can change it to intel (nasm's syntax)
with the command `set disassembly-flavor intel`


== Change a number from little endian to big endian in C

[source, c]
----
#include <stdio.h>
#include <stdlib.h>
#include <arpa/inet.h>

int
main(void){
    unsigned int num = 0x12345678;
    printf("%x\n", htonl(num));
}
----

== Strings
To explicitly state the length of a string:

[source, nasm]
----
db 27, 'Selling England by the Pound'
----

== Constant Precomputation
The math in the code belows is calculated at compile time and turned into a
constant

[source, nasm]
----
lab: db 0

mov rax, lab + 1 + 2 *3 
----

== Pointers and Differnt Addressing Types
Pointers are 8 bytes.

you need to specify operation size, when trying to write shomewhere a value
whose size is not specified.

[source, nasm]
----
section .data
    test: dq -1
section .bss
section .text
	global main
main:
   mov byte[test], 1 
    ;mov [test], 1 ; gives an error
   mov word[test], 1
   mov dword[test], 1
   mov qword[test], 1

	mov  rax, 60
	mov rdi, 0 
	syscall
----

== Two's complement
1. Do a logical not to all the bits
2. add 1

== Instructions
=== NEG
The `NEG` instruction applys two complement. It sets the CF falgs to zero if the
source operand is 0; otherwise it is set to 1.

=== IMUL
signed multiplication

One-operand form::
    secound operand is in AL, AX, EAX, or RAX, depending on the
    size

Two-operand form::
    With this form the destination operand (the first operand) is multiplied by
    the source operand

Three-operand form::
    with `mul a, b, c`, the multiplication of `b` and `c` is
    stored in `a`

=== MUL
unsigned multiply

the source operand is located in either AL, AX, or EAX, dending on the size of
the operand.

=== SUB
subtract source operand from the destination operand and stores the result in
the destination operand.

- integer subraction; signed and unsigned

- sets OF flags to indicate an overflow in the signed or unsigned result,
  respectively.

- The SF flag indicates the sign of the signed result

In 64-bit mode the instruction's default operation size is 32 bits

=== IDIV
signed divide. Divides the value in AX, DX:AX, or EDX:EAX (dividend) by the
source operand (divisor) and stores the result in AX (AH:AL), DX:AX, or EDX:EAX
registers.

- Overflow is indicated withthe #DE (divide error) exception rather than with
  the CF flag

=== DIV
Divids unsigned the value in the AX, DX:AX, EDX:EAX, or RDX:RAX registers
(dividend) by the source operand (divisor) and stores the result in AX (AH:AL),
DX:AX, EDX:EAX, or RDX:RAX register

example:

[source, nasm]
----
; Because the  dividend is RDX:RAX, we need to clear RDX and RAX
xor rdx, rdx
xor rax, rax

mov rax, 10 ; dividend (top)
mov rcx, 5 ; divisor (bottom)
div rcx  ; result is stored in RDX:RAX
mov rdi, rax ; returning the result as a exit number

mov rax, 60 ; exit syscall
syscall
----

== EDX:EAX ??
?

== NASM and gdb
=== Flavor

to set dissasembly flavor to intel instead of AT&T:

[source, gdb]
----
set disassembly-flavor intel
----

=== Dissassembly a function

[source, gdb]
----
disassemble <function name>
----

* **function name** - can be the name of any function (i.e main)


=== Finding Immediate value
If you have

[source, nasm]
----
msg db "hello, world", 10, 0
----

In the `.data` section and use it later with

[source, nasm]
----
mov rsi, msg
----

The output of `(gdb) dissassembly <function name>` might look something like
this

[source, nasm]
----
0x000000000040111a <+10>:    movabs rsi,0x404028
----

You can see what is inside the memory address `0x404028` with

[source, gdb]
----
(gdb) x/s 0x404028
0x404028 <msg>: "hello, world\n"
----

As you can see that is the address is where `msg` is located

NOTE: checkout `(gdb) help x`

* **x/s** - output string
* **x/c** -output character
* **x/13c** -output 13 characters
* **x/13d** -output 13 characters in decimal representation

=== TUI
[source, gdb]
----
(gdb) tui <enable/disable>
----

=== Registers
[source, gdb]
----
(gdb) info registers
----

=== Source code
[source, gdb]
----
(gdb) list <nothing or line number>
----

=== Steping through Instructions
.next_asm.gdb
[source, gdb]
----
set language asm
set disassembly-flavor intel
define asm_next
nexti
disassemble
end
----

[source, sh]
----
$ gdb -x next_asm.gdb <executable>
----


== Real vs Protected vs long Mode
- https://en.wikipedia.org/wiki/X86_memory_segmentation

"A 386 CPU can be put back into real mode by clearing a bit in the CR0 control
register, however this is a privileged operation in order to enforce security
and robustness"
-- X86_memory_segmentation, Wikipedia

== Segment Registers

Logical addresses can be explicitly specified in *x86 assembly language

all segments have a base of zero

In protected mode, code may always modify all segment registers except CS (the
code segment selector). This is because the current privilege level (CPL) of the
processor is stored in the lower 2 bits of the CS register

The only ways to raise the processor privilege level (and reload CS) are through
the lcall (far call) and int (interrupt) instructions. Similarly, the only ways
to lower the privilege level (and reload CS) are through lret (far return) and
iret (interrupt return) instructions. In real mode, code may also modify the CS
register by making a far jump (or using an undocumented POP CS instruction on
the 8086 or 8088).[4] Of course, in real mode, there are no privilege levels;
all programs have absolute unchecked access to all of memory and all CPU
instructions

[source, asm]
----
movl $42, %fs:(%eax)  ; Equivalent to M[fs:eax]<-42) in RTL
----

or in intel syntax

[source, nasm]
----
mov dword [fs:eax], 42
----

* What data is in each segment
    - All CPU instructions are implicitly fetched from the code segment
      specified by the segment selector held in the CS register.

    - Most memory references come from the data segment specified by the segment
      selector held in the DS register. These may also come from the extra
      segment specified by the segment selector held in the ES register, if a
      segment-override prefix precedes the instruction that makes the memory
      reference. Most, but not all, instructions that use DS by default will
      accept an ES override prefix.

    - Processor stack references, either implicitly (e.g. push and pop
      instructions) or explicitly (memory accesses using the (E)SP or (E)BP
      registers) use the stack segment specified by the segment selector held in
      the SS register.

    - String instructions (e.g. stos, movs), along with data segment, also use
      the extra segment specified by the segment selector held in the ES
      register.

    - mov is used to manipulate data, so the address is relative to the data
      segment

== Compiling and Linking
=== Makefile
The `-f` is follow by the output format, in our case elf64, which means
Executable and Linkable Format for 64-bit. The `-g` mains that we include debug
information in a debug format specified adter the `-F` option. We use dwarf
debug format. The `-l` tells NASM to generate a _.lst_ file. Nasm will create an
object file with a _.o_ extension. That object file is used by the linker.

DWARF::
    Debug With **A**rbitrary **R**ecord **F**ormat

STABS::
    Debug with **S**ymbol **T**able **S**trings.

elf64::
    Executable and linkable Format for 64-bit

PIE::
    **P**osition-**I**ndependant **E**xecutables

== NO-OP
The x86-64 ISA includes several no-op (no operation) instructions, including
`nop`, `nop A,` (no-op with an argument), and `data16`. No-ops do pretty much
nothing, but do set the rflags. The main reason for no-ops is to optimize
instruction memory (e.g., code size, alignment).

== Modes
- Real mode (the most ancient, 16-bit)
    * Computer is booted into this mode
    * Can access pretty much any memory location
    * No virtual memory
- Protected (commonly referred as 32-bit one)
    * Virtual memory
    * Protection rings
    * Improved segmentation
- Virtual (to emulate real mode inside protected)
- System management mode (for sleep mode, power management, etc)
- Long Mode
    * Virtual memory

== Memory Addresses
If you look at this _.lst_ file you can see the each memory address (second
column) has 8 hexadecimal digits meaning that there are 64 bits per instruction.
This is because we are using 64 bit assembler.

.\.lst file
[code, lst]
----
    11 00000000 B801000000                  mov rax, 1
    12 00000005 BF01000000                  mov rdi, 1
----

== Books
- "Learn to Program with Assembly by Jonathan Bartlett"
    * learning AT&T syntax with GNU assembler

- "Low-Level Programming by Igor Zhirkov" 
    * intel syntax

== Links
- https://www.felixcloutier.com/x86/[x86 and amd64 instruction reference]
- https://www.intel.com/content/www/us/en/developer/articles/technical/intel-sdm.html[intel 64 IA-32 architectures Software Developer's Manual]
- https://redirect.cs.umbc.edu/portal/help/nasm/nasm.shtml[nasm and gdb]
- https://refspecs.linuxfoundation.org/elf/x86_64-abi-0.99.pdf[System V Application Binary Interface AMD64]
- https://electronicsreference.com/assembly-language/linux_syscalls/[linux syscalls]
- https://blog.packagecloud.io/the-definitive-guide-to-linux-system-calls/[more on linux syscalls]
- https://github.com/torvalds/linux/blob/v3.13/arch/x86/syscalls/syscall_32.tbl[linux source code syscall table]
- https://stackoverflow.com/questions/15017659/how-to-read-the-intel-opcode-notation[op code notation]
- https://stackoverflow.com/questions/10684468/missing-debugging-information-with-gdb-and-nasm[debugging asm_next script nasm and gdb]
